### ISSUE TITLE
Crash on custom support change

### ISSUE THREAD

**Issue by riktheunissen** [BlackBelt3D/Cura#17]
**Application Version**
3.5 beta

**Platform**
W10

**Printer**
BB3D

**Steps to Reproduce**

- Open the project load the files
- Merge the files, ctrl click the supposed support
- Set to support, Cura crashes.
- Open Cura again (same steps) crashes,
- Every new projects crash on change to print as support.
- Even moving the object slightly doesn't affect it (this sometimes worked in 3.4)

**Actual Results**
Cura shuts down and corrupts the config

**Expected results**
change to support structure

**Additional Information**
[35_04_PLA_Profile_100.zip](https://github.com/BlackBelt3D/Cura/files/2414818/35_04_PLA_Profile_100.zip)
[cura.log](https://github.com/BlackBelt3D/Cura/files/2415019/cura.log)

**Comment by fieldOfView** [comment]
Could you please clarify? Your first step to reproduce is "open it again". Open what again? I don't understand what you are trying to say.

**Comment by riktheunissen** [comment]
updated the steps

**Comment by riktheunissen** [comment]
actually it just closes after every change of mesh type to "print as support". Maybe it is not a crash. I added a log of a random file changed mesh type to "print as support".

**Comment by fieldOfView** [comment]
Thanks, much clearer now. I have reproduced the same issue in Ultimaker Cura 3.5 (with any printer), so I will report it in the main project while trying to find a fix.

**Comment by fieldOfView** [comment]
Has been fixed for 3.5
