### ISSUE TITLE
Installation file on MAC recently stopped working / was working before.

### ISSUE THREAD

**Issue by BBStephan** [BlackBelt3D/Cura#20]
**Application Version**
3.5.1

**Platform**
OSX

**Steps to Reproduce**
Try to install BLACKBELT Cura 3.5.1 on a Mac

**Actual Results**
Error message: "BlackBelt Cura" is damaged and can't be opened. You should eject the disk image.
![error](https://user-images.githubusercontent.com/32984892/47914050-74c3fb00-de9e-11e8-9483-8f11ebbbabca.png)

**Expected results**
BLACKBELT Cura 3.5.1 should install and open like on a normal PC.

**Additional Information**
Reproduced error on Mac OS X 10.14 Mojave

**Comment by riktheunissen** [comment]
Also occurs on BlackBelt Cura 3.6.0, works on some mac's and doesn't on others. Haven't found a good way to debug it.
