### ISSUE TITLE
Prefix does not update when changing configuration

### ISSUE THREAD

**Issue by riktheunissen** [BlackBelt3D/Cura#23]
**Application Version**
3.6.0 BETA

**Platform**
W10

**Printer**
BB

**Steps to Reproduce**
Check it at three different installations all windows

**Actual Results**
no name change on settings change

**Expected results**
name change on settings change

**Additional Information**

![image](https://user-images.githubusercontent.com/42371563/48850413-e65ddd80-eda8-11e8-9bfd-3dfd5d0b47f9.png)

**Comment by fieldOfView** [comment]
Reproduced. Working on a fix.

**Comment by fieldOfView** [comment]
Fixed in d2e5ba5
