### ISSUE TITLE
Custom Support Plug-In installed by default

### ISSUE THREAD

**Issue by BBStephan** [BlackBelt3D/Cura#24]
**Application Version**
3.6

**Printer**
BLACKBELT 3D

**Steps to Reproduce**
Marketplace - Custom Support - Install

**Actual Results**
Not installed by default

**Expected results**
It would be super handy to have it from the beginning.

**Additional Information**
Custom Support Plug-In version 0.0.3 by Krasimir Stefanov

**Comment by fieldOfView** [comment]
I will also add the OctoPrint Connection plugin.

**Comment by fieldOfView** [comment]
Implemented
