### ISSUE TITLE
Nozzle Size selections

### ISSUE THREAD

**Issue by jamskate** [BlackBelt3D/Cura#28]
**Application Version**
3.6.0

**Platform**
Windows 10

**Printer**
White Knight Custom Belt printer

Is there a way to add more Nozzle sizes to the drop down?  I'd like to have support up to 1.2mm.

Thanks

**Comment by BBStephan** [comment]
Should be doable,
In the meantime, you can set your specific nozzle diameter via "Line Width" - which is all that the drop-down is doing.

**Comment by jamskate** [comment]
Thanks, for the tip!!!
