### ISSUE TITLE
Maximum Z speed

### ISSUE THREAD

**Issue by jamskate** [BlackBelt3D/Cura#29]
**Application Version**
3.6.0
**Platform**
Windows 10

**Printer**
White Knight Belt Printer

**Additional Information**
My Z-axis layer shift seems to be very slow..  I've tried all setting I can on my Duet and I believe it may be part of how its sliced..  I tried to enable "Maximum Z Speed" but it tells me "This setting has been hidden by the active machine and will not be visible".  Is there a way to enable this feature or change the value elsewhere?

Thanks

**Comment by BBStephan** [comment]
It's most likely it's a duet issue.
Using the default settings, we are not limiting the Z speed in Cura.
