### ISSUE TITLE
An error was reported during the process of compiling the source code, which seems to be a loop import problem of python.

### ISSUE THREAD

**Issue by sorrowfeng** [BlackBelt3D/Cura#42]
**cura-bb-3.6**
 Compilation failed 

**Windows**
 I reported an error in the process of compiling the source code, which seems to be the problem of circular import of python.
I replaced the Cura,Uranium and fdm_materials files during the compilation of the original cura. 
Is there something wrong with my process? 

This is an error message.
  File "C:\dev\Uranium\UM\FileHandler\ReadFileJob.py", line 5, in <module>
    from UM.Application import Application
ImportError: cannot import name 'Application'

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by fieldOfView** [comment]
Only the official builds of Blackbelt Cura are supported here. For questions on how to build Cura, refer to the Ultimaker Cura repository.
