### ISSUE TITLE
Filament ejects during a print when "Belt Wall Flow" is changed

### ISSUE THREAD

**Issue by BBStephan** [BlackBelt3D/Cura#8]
**Application Version**

3.4.2

**Steps to Reproduce**

Set "Belt wall flow" to a number other than 100%

**Actual Results**

Big parts will fully retract the filament after a while

**Additional Information**

We could spot the bug here (line 24292, E turns negative):
![whatsapp image 2018-08-15 at 13 41 39](https://user-images.githubusercontent.com/32984892/44159289-3eed5280-a0b7-11e8-8a03-a8089db9952b.jpeg)

**Comment by fieldOfView** [comment]
I will try to reproduce this (and fix it)

Could you check if the `G92 E0` is also there if you set Belt wall flow to 100%?
Does this also happen without "print as support" meshes?

**Comment by fieldOfView** [comment]
Could you send me the full gcode file (and preferably the model(s)) so I can check it out?

**Comment by fieldOfView** [comment]
It seems the G92 E0 is indeed the issue. I have identified why this is added in the first place (there's a good reason), and will fix BB Cura to handle it properly.

**Comment by riktheunissen** [comment]
Thanks for that, do you need anything from our part? I can send the project and the models if you still need them.
